### ISSUE TITLE
Add an issue template for code-along and questions

### ISSUE THREAD

**Issue by LovelySanta** [TheCherno/Hazel#269]
#### Is your feature request related to a problem? Please describe
As recently discovered in [TheChernoCommunity/HazelWiki](https://github.com/TheChernoCommunity/HazelWiki), I discovered (thanks to @cxgslegend) that we can add a link to the issue templates. This way we can provide a quick way to our discord for code along questions (for example #267)

#### Describe the solution you'd like
Include an extra issue template with a link to the cherno discord, similar as in [TheChernoCommunity/HazelWiki/issues](https://github.com/TheChernoCommunity/HazelWiki/issues/new/choose).

#### Describe alternatives you've considered
We already mention this in every issue template, but there are still issues with questions coming in (see for example #267 recently).

#### Additional context
The example of the issue template link as shown in [TheChernoCommunity/HazelWiki/issues](https://github.com/TheChernoCommunity/HazelWiki/issues/new/choose) is added by adding a [config.yml](https://github.com/TheChernoCommunity/HazelWiki/blob/08a53860a0062350e5a04dca2cc021a27f912e93/.github/ISSUE_TEMPLATE/config.yml) file, similar to:
```yml

blank_issues_enabled: false
contact_links:
  - name: Hazel Community Support
    url: https://thecherno.com/discord
    about: Please ask Hazel related questions in the game-engine-series thread.
```
