### ISSUE TITLE
Loaded scene, problem with transparency

### ISSUE THREAD

**Issue by Masterride05** [TheCherno/Hazel#386]
#### Description
If you load a scene, in which squares have transparency, the squares won't blend (even if the alpha channel gets changed)

#### To Reproduce
1. Save a scene with multiple squares with transparency (with different z-positions*)
2. Open new scene
3. Open the saved scene again
4. you should see the square in front not blending, along with every other square

#### Example
Here is my scene file

```
Scene: Untitled
Entities:
  - Entity: 12837192831273
    TagComponent:
      Tag: Square3
    TransformComponent:
      Translation: [0, 0, -0.0199999996]
      Rotation: [0, 0, 0]
      Scale: [1, 1, 1]
    SpriteRendererComponent:
      Color: [1, 0.70588237, 0, 0.501960814]
  - Entity: 12837192831273
    TagComponent:
      Tag: Square2
    TransformComponent:
      Translation: [0, 0, -0.00999999978]
      Rotation: [0, 0, 0]
      Scale: [1, 1, 1]
    SpriteRendererComponent:
      Color: [0, 1, 0.117647059, 0.501960814]
  - Entity: 12837192831273
    TagComponent:
      Tag: Square
    TransformComponent:
      Translation: [0, 0, 0]
      Rotation: [0, 0, 0]
      Scale: [1, 1, 1]
    SpriteRendererComponent:
      Color: [0, 0.588235319, 1, 0.501960814]
  - Entity: 12837192831273
    TagComponent:
      Tag: Camera
    TransformComponent:
      Translation: [1.85000002, 0, 2]
      Rotation: [0, 0.785398185, 0]
      Scale: [0.579999983, 1, 1]
    CameraComponent:
      Camera:
        ProjectionType: 0
        PerspectiveFOV: 1.04719758
        PerspectiveNear: 0.00999999978
        PerspectiveFar: 1000
        OrthographicSize: 10
        OrthographicNear: -1
        OrthographicFar: 1
      Primary: true
      FixedAspectRatio: false
```
